/**
 * 批量打印的数据源
 */
Ext.define(//
    "cn.com.pingouin.vbp_client_samples.xian_jin_bao_xiao_shen_qing.VbpDataSource"//
    , {
      
      extend : "",
      
      config : {
        datas : [//
        {
              "id" : "1",
              "shenQingRen" : "张三",
              "yuanGongHao" : "12345",
              "buMen" : "产品研发中心",
              "riQiNian" : "2013",
              "riQiYue" : "10",
              "riQiRi" : "22",
              "feiYongBianHao_1" : "1",
              "zhaiYao_1" : "餐费",
              "chengBenZhongXin_1" : "",
              "jinEWan_1" : "",
              "jinEQian_1" : "",
              "jinEBai_1" : "9",
              "jinEShi_1" : "8",
              "jinEYuan_1" : "1",
              "jinEJiao_1" : "0",
              "jinEFen_1" : "0",
              "feiYongBianHao_2" : "2",
              "zhaiYao_2" : "交通费",
              "chengBenZhongXin_2" : "",
              "jinEWan_2" : "",
              "jinEQian_2" : "",
              "jinEBai_2" : "9",
              "jinEShi_2" : "6",
              "jinEYuan_2" : "1",
              "jinEJiao_2" : "0",
              "jinEFen_2" : "0",
              "heJiDaXieWan" : "<img src=\"images/xian_jin_bao_xiao_shen_qing/cross_in_cycle.png\" width=\"16px\" height=\"16px\"></img>",
              "heJiDaXieQian" : "壹",
              "heJiDaXieBai" : "玖",
              "heJiDaXieShi" : "肆",
              "heJiDaXieYuan" : "贰",
              "heJiDaXieJiao" : "零",
              "heJiDaXieFen" : "零",
              "heJiJinEWan" : "&#165;",
              "heJiJinEQian" : "1",
              "heJiJinEBai" : "9",
              "heJiJinEShi" : "4",
              "heJiJinEYuan" : "2",
              "heJiJinEJiao" : "0",
              "heJiJinEFen" : "0",
              "fuJian" : "47",
              //
              nothing : null
            }, {
              "id" : "2",
              "shenQingRen" : "李四",
              "yuanGongHao" : "23456",
              "buMen" : "产品研发中心",
              "riQiNian" : "2013",
              "riQiYue" : "10",
              "riQiRi" : "22",
              "feiYongBianHao_1" : "1",
              "zhaiYao_1" : "餐费",
              "chengBenZhongXin_1" : "",
              "jinEWan_1" : "",
              "jinEQian_1" : "",
              "jinEBai_1" : "9",
              "jinEShi_1" : "8",
              "jinEYuan_1" : "1",
              "jinEJiao_1" : "0",
              "jinEFen_1" : "0",
              "feiYongBianHao_2" : "2",
              "zhaiYao_2" : "交通费",
              "chengBenZhongXin_2" : "",
              "jinEWan_2" : "",
              "jinEQian_2" : "",
              "jinEBai_2" : "9",
              "jinEShi_2" : "6",
              "jinEYuan_2" : "1",
              "jinEJiao_2" : "0",
              "jinEFen_2" : "0",
              "heJiDaXieWan" : "<img src=\"images/xian_jin_bao_xiao_shen_qing/cross_in_cycle.png\" width=\"16px\" height=\"16px\"></img>",
              "heJiDaXieQian" : "壹",
              "heJiDaXieBai" : "玖",
              "heJiDaXieShi" : "肆",
              "heJiDaXieYuan" : "贰",
              "heJiDaXieJiao" : "零",
              "heJiDaXieFen" : "零",
              "heJiJinEWan" : "&#165;",
              "heJiJinEQian" : "1",
              "heJiJinEBai" : "9",
              "heJiJinEShi" : "4",
              "heJiJinEYuan" : "2",
              "heJiJinEJiao" : "0",
              "heJiJinEFen" : "0",
              "fuJian" : "47",
              //
              nothing : null
            }, {
              "id" : "3",
              "shenQingRen" : "王五",
              "yuanGongHao" : "34567",
              "buMen" : "产品研发中心",
              "riQiNian" : "2013",
              "riQiYue" : "10",
              "riQiRi" : "22",
              "feiYongBianHao_1" : "1",
              "zhaiYao_1" : "餐费",
              "chengBenZhongXin_1" : "",
              "jinEWan_1" : "",
              "jinEQian_1" : "",
              "jinEBai_1" : "9",
              "jinEShi_1" : "8",
              "jinEYuan_1" : "1",
              "jinEJiao_1" : "0",
              "jinEFen_1" : "0",
              "feiYongBianHao_2" : "2",
              "zhaiYao_2" : "交通费",
              "chengBenZhongXin_2" : "",
              "jinEWan_2" : "",
              "jinEQian_2" : "",
              "jinEBai_2" : "9",
              "jinEShi_2" : "6",
              "jinEYuan_2" : "1",
              "jinEJiao_2" : "0",
              "jinEFen_2" : "0",
              "heJiDaXieWan" : "<img src=\"images/xian_jin_bao_xiao_shen_qing/cross_in_cycle.png\" width=\"16px\" height=\"16px\"></img>",
              "heJiDaXieQian" : "壹",
              "heJiDaXieBai" : "玖",
              "heJiDaXieShi" : "肆",
              "heJiDaXieYuan" : "贰",
              "heJiDaXieJiao" : "零",
              "heJiDaXieFen" : "零",
              "heJiJinEWan" : "&#165;",
              "heJiJinEQian" : "1",
              "heJiJinEBai" : "9",
              "heJiJinEShi" : "4",
              "heJiJinEYuan" : "2",
              "heJiJinEJiao" : "0",
              "heJiJinEFen" : "0",
              "fuJian" : "47",
              //
              nothing : null
            }],
        //
        nothing : null
      },
      
      //
      nothing : null
    }//
);
